import { CaseData } from '@/lib/types/patient';

export const data: CaseData[] = [
  {
    caseBundlingId: 2093,
    cancerType: 'All Cancer Types',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Sun May 19 2024',
    status: 'Paused Review',
  },
  {
    caseBundlingId: 93810,
    cancerType: 'Myelomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Thu Apr 18 2024',
    status: 'Waiting for Review',
  },
  {
    caseBundlingId: 13545,
    cancerType: 'Carcinomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Fri Nov 22 2024',
    status: 'Waiting for Review',
  },
  {
    caseBundlingId: 81457,
    cancerType: 'Sarcomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Thu Feb 06 2025',
    status: 'Needs Review',
  },
  {
    caseBundlingId: 74445,
    cancerType: 'Melanoma',
    project: 'Merk MIBC',
    lastExtraction: 'Tue Oct 08 2024',
    status: 'Needs Review',
  },
  {
    caseBundlingId: 38651,
    cancerType: 'Carcinomas',
    project: 'Merk TNBC',
    lastExtraction: 'Mon Feb 03 2025',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 76148,
    cancerType: 'Carcinomas',
    project: 'Merk MIBC',
    lastExtraction: 'Wed Dec 11 2024',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 32159,
    cancerType: 'Myelomas',
    project: 'Merk TNBC',
    lastExtraction: 'Sat Oct 12 2024',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 24517,
    cancerType: 'Myelomas',
    project: 'Merk MIBC',
    lastExtraction: 'Fri Nov 22 2024',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 54618,
    cancerType: 'Leukemias',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Fri Jul 26 2024',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 88874,
    cancerType: 'Carcinomas',
    project: 'Merk MIBC',
    lastExtraction: 'Sat Mar 30 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 53215,
    cancerType: 'Myelomas',
    project: 'Merk TNBC',
    lastExtraction: 'Mon Oct 14 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 68640,
    cancerType: 'Leukemias',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Fri Jun 21 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 39371,
    cancerType: 'Myelomas',
    project: 'Merk MIBC',
    lastExtraction: 'Fri May 10 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 15669,
    cancerType: 'Carcinomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Sat Nov 16 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 98293,
    cancerType: 'Carcinomas',
    project: 'Merk TNBC',
    lastExtraction: 'Thu Jun 06 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 45678,
    cancerType: 'Myelomas',
    project: 'Merk MIBC',
    lastExtraction: 'Wed Mar 13 2024',
    status: 'Needs Review',
  },
  {
    caseBundlingId: 45679,
    cancerType: 'Carcinomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Thu Mar 14 2024',
    status: 'Waiting for Review',
  },
  {
    caseBundlingId: 45680,
    cancerType: 'Leukemias',
    project: 'Merk TNBC',
    lastExtraction: 'Fri Mar 15 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 45681,
    cancerType: 'Myelomas',
    project: 'Merk MIBC',
    lastExtraction: 'Sat Mar 16 2024',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 45682,
    cancerType: 'Carcinomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Sun Mar 17 2024',
    status: 'Paused Review',
  },
  {
    caseBundlingId: 45683,
    cancerType: 'Leukemias',
    project: 'Merk TNBC',
    lastExtraction: 'Mon Mar 18 2024',
    status: 'Needs Review',
  },
  {
    caseBundlingId: 45684,
    cancerType: 'Myelomas',
    project: 'Merk MIBC',
    lastExtraction: 'Tue Mar 19 2024',
    status: 'Waiting for Review',
  },
  {
    caseBundlingId: 45685,
    cancerType: 'Carcinomas',
    project: 'Technicolor Beta Physician',
    lastExtraction: 'Wed Mar 20 2024',
    status: 'Reviewed',
  },
  {
    caseBundlingId: 45686,
    cancerType: 'Leukemias',
    project: 'Merk TNBC',
    lastExtraction: 'Thu Mar 21 2024',
    status: 'Awaiting Response',
  },
  {
    caseBundlingId: 45687,
    cancerType: 'Myelomas',
    project: 'Merk MIBC',
    lastExtraction: 'Fri Mar 22 2024',
    status: 'Paused Review',
  },
];
